services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbusr
      POSTGRES_PASSWORD: dbpwd
    volumes:
      - postgres_data:/var/lib/postgres/data # persistent data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      # ASAP - as simple as possible
      PGADMIN_DEFAULT_EMAIL: me@me.me
      PGADMIN_DEFAULT_PASSWORD: me
    ports:
      - 8001:80 # runs externally on localhost:8001
    depends_on:
      - postgres

volumes:
  postgres_data:
